name: "GitHub Organization API"
author: ""
description: ""
branding:
  icon: ""
  color: ""
inputs:
  git_repo:
    description: "Git Repository"
    required: true
  git_user:
    description: "Git User"
    required: true
  git_email:
    description: "Git E-mail"
    required: true
  git_token:
    description: "Git Token"
    required: true
  api_dir:
    description: "Local API Directory"
    required: true
    default: "api/github"
  api_owner:
    description: "GitHub API Owner"
    required: true
  api_token:
    description: "GitHub API Token"
    required: true
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.git_repo }}
    - ${{ inputs.git_user }}
    - ${{ inputs.git_email }}
    - ${{ inputs.git_token }}
    - ${{ inputs.api_dir }}
    - ${{ inputs.api_owner }}
    - ${{ inputs.api_token }}
